import { HabilitationType, PlatformType, UserAgent } from './types';

export const TAX_CENTERS: string[] = [
  'CENTRE DES MOYENNES ENTREPRISES DAKAR 2',
  'CENTRE DES MOYENNES ENTREPRISES DAKAR 1',
  'GRAND-DAKAR',
  'PIKINE',
  'RUFISQUE',
  'MATAM',
  'PARCELLES ASSAINIES',
  'GUEDIAWAYE',
  'ZIGUINCHOR',
  'DIOURBEL',
  'SAINT-LOUIS',
  'KAOLACK',
  'THIES',
  'LOUGA',
  'KOLDA',
  'FATICK',
  'MBOUR',
  'TAMBACOUNDA',
  'DAKAR-LIBERTE',
  'NGOR-ALMADIES',
  'KEDOUGOU',
  'KAFFRINE',
  'SEDHIOU',
  'DAKAR-PLATEAU',
  'CPR',
  'DIRECTION DES GRANDES ENTREPRISES',
  'KEUR MASSAR',
  'DIAMNIADIO',
  'TIVAOUANE',
  'DRESCO',
  'DCL',
  'DAP',
  'BCOM/CEFOD',
  'DIRECTION GENERALE',
  'DSF',
  'DIRECTION RECOUVREMENT',
  'CADASTRE',
  'DIRECTION DES DOMAINES',
  'Direction des Systèmes d\'Information',
];

export const PLATFORMS: PlatformType[] = [
  'SENTAX BACK OFFICE',
  'SENTAX CONTRIBUABLE',
  'SENTAX EBANQUE',
  'E-SERVICES',
  'MON ESPACE-PERSO',
  'SEN-ETAFI',
  'MPAY',
  'SENTIMBRES',
  'DGID-DIGITAL',
  'PCF',
  'COFI',
  'Autre',
];

export const HABILITATIONS: HabilitationType[] = [
  'Directeur / CT',
  'Chef de Centre / Chef de Division',
  'Chef de Bureau',
  'Chef de Section / UGF',
  'Agent d\'Assiette',
  'Comptable',
];

export const INITIAL_AGENTS: UserAgent[] = [
  {
    id: 'agent-001',
    firstName: 'Amadou',
    lastName: 'Diagne',
    email: 'amadou.diagne@dgid.sn',
    phone: '+221 77 654 32 10',
    matricule: 'DGID-654321',
    role: 'SUPERADMIN',
    habilitation: 'Chef de Centre / Chef de Division',
    poste: 'Administrateur Système Support SENTAX',
    bureau: 'Bureau Informatique DSI',
    direction: 'Direction des Systèmes d\'Information',
    status: 'ACTIVE',
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'agent-002',
    firstName: 'Fatou',
    lastName: 'Fall',
    email: 'fatou.fall@dgid.sn',
    phone: '+221 78 123 45 67',
    matricule: 'DGID-781234',
    role: 'ADMIN',
    habilitation: 'Chef de Bureau',
    poste: 'Superviseur Support Technique',
    bureau: 'Bureau Assistance Utilisateurs',
    direction: 'Direction des Systèmes d\'Information',
    status: 'ACTIVE',
    createdAt: '2025-01-15T09:30:00Z',
  },
  {
    id: 'agent-003',
    firstName: 'Ousmane',
    lastName: 'Ndiaye',
    email: 'ousmane.ndiaye@dgid.sn',
    phone: '+221 70 987 65 43',
    matricule: 'DGID-987654',
    role: 'AGENT',
    habilitation: 'Agent d\'Assiette',
    poste: 'Technicien Support Niveau 2',
    bureau: 'Bureau Exploitation et Réseaux',
    direction: 'Direction des Systèmes d\'Information',
    status: 'ACTIVE',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'agent-004',
    firstName: 'Awa',
    lastName: 'Sow',
    email: 'awa.sow@dgid.sn',
    phone: '+221 76 555 12 34',
    matricule: 'DGID-555123',
    role: 'AGENT',
    habilitation: 'Agent d\'Assiette',
    poste: 'Chargée d\'Assistance Utilisateurs',
    bureau: 'Bureau Helpdesk',
    direction: 'Direction des Systèmes d\'Information',
    status: 'ACTIVE',
    createdAt: '2025-03-01T11:00:00Z',
  },
];

export const OFFICIAL_SUPPORT_EMAIL = 'support-technique-sentax@dgid.sn';
